set -l test_dir (dirname (status filename))
source $test_dir/../functions/taskwarrior_parse_date.fish

@test "AST: 昨天 -> sod-1d" (_task_parse_date 昨天) = "sod-1d"
@test "AST: 現在 -> now" (_task_parse_date 現在) = "now"
@test "AST: 现在 -> now" (_task_parse_date 现在) = "now"
@test "AST: 今天 -> sod+0d" (_task_parse_date 今天) = "sod+0d"
@test "AST: 明天 -> sod+1d" (_task_parse_date 明天) = "sod+1d"
@test "AST: 後天 -> sod+2d" (_task_parse_date 後天) = "sod+2d"
@test "AST: 后天 -> sod+2d" (_task_parse_date 后天) = "sod+2d"
@test "AST: 大後天 -> sod+3d" (_task_parse_date 大後天) = "sod+3d"
@test "AST: 大后天 -> sod+3d" (_task_parse_date 大后天) = "sod+3d"

@test "AST: 週末 -> eow" (_task_parse_date 週末) = "eow"
@test "AST: 周末 -> eow" (_task_parse_date 周末) = "eow"
@test "AST: 這週末 -> eow" (_task_parse_date 這週末) = "eow"
@test "AST: 這周末 -> eow" (_task_parse_date 這周末) = "eow"
@test "AST: 这周末 -> eow" (_task_parse_date 这周末) = "eow"
@test "AST: 上週 -> sopw" (_task_parse_date 上週) = "sopw"
@test "AST: 上周 -> sopw" (_task_parse_date 上周) = "sopw"
@test "AST: 上週末 -> eopw" (_task_parse_date 上週末) = "eopw"
@test "AST: 上周末 -> eopw" (_task_parse_date 上周末) = "eopw"
@test "AST: 上個週末 -> eopw" (_task_parse_date 上個週末) = "eopw"
@test "AST: 上個周末 -> eopw" (_task_parse_date 上個周末) = "eopw"
@test "AST: 上个周末 -> eopw" (_task_parse_date 上个周末) = "eopw"
@test "AST: 下週 -> sonw" (_task_parse_date 下週) = "sonw"
@test "AST: 下周 -> sonw" (_task_parse_date 下周) = "sonw"
@test "AST: 下週末 -> eonw" (_task_parse_date 下週末) = "eonw"
@test "AST: 下周末 -> eonw" (_task_parse_date 下周末) = "eonw"
@test "AST: 下個週末 -> eonw" (_task_parse_date 下個週末) = "eonw"
@test "AST: 下個周末 -> eonw" (_task_parse_date 下個周末) = "eonw"
@test "AST: 下个周末 -> eonw" (_task_parse_date 下个周末) = "eonw"

@test "AST: 月初 -> som" (_task_parse_date 月初) = "som"
@test "AST: 這個月初 -> som" (_task_parse_date 這個月初) = "som"
@test "AST: 这个月初 -> som" (_task_parse_date 这个月初) = "som"
@test "AST: 月底 -> eom" (_task_parse_date 月底) = "eom"
@test "AST: 這個月底 -> eom" (_task_parse_date 這個月底) = "eom"
@test "AST: 这个月底 -> eom" (_task_parse_date 这个月底) = "eom"
@test "AST: 上個月初 -> sopm" (_task_parse_date 上個月初) = "sopm"
@test "AST: 上个月初 -> sopm" (_task_parse_date 上个月初) = "sopm"
@test "AST: 上個月底 -> eopm" (_task_parse_date 上個月底) = "eopm"
@test "AST: 上个月底 -> eopm" (_task_parse_date 上个月底) = "eopm"
@test "AST: 下個月初 -> sonm" (_task_parse_date 下個月初) = "sonm"
@test "AST: 下个月初 -> sonm" (_task_parse_date 下个月初) = "sonm"
@test "AST: 下個月底 -> eonm" (_task_parse_date 下個月底) = "eonm"
@test "AST: 下个月底 -> eonm" (_task_parse_date 下个月底) = "eonm"

@test "AST: 年初 -> soy" (_task_parse_date 年初) = "soy"
@test "AST: 年底 -> eoy" (_task_parse_date 年底) = "eoy"
@test "AST: 今年年初 -> soy" (_task_parse_date 今年年初) = "soy"
@test "AST: 今年年底 -> eoy" (_task_parse_date 今年年底) = "eoy"
@test "AST: 前年初 -> sony" (_task_parse_date 前年初) = "sony"
@test "AST: 前年底 -> eony" (_task_parse_date 前年底) = "eony"
@test "AST: 前年年初 -> sopy" (_task_parse_date 前年年初) = "sopy"
@test "AST: 前年年底 -> eopy" (_task_parse_date 前年年底) = "eopy"
@test "AST: 明年初 -> sony" (_task_parse_date 明年初) = "sony"
@test "AST: 明年底 -> eony" (_task_parse_date 明年底) = "eony"
@test "AST: 明年年初 -> sony" (_task_parse_date 明年年初) = "sony"
@test "AST: 明年年底 -> eony" (_task_parse_date 明年年底) = "eony"
