set -l test_dir (dirname (status filename))
source $test_dir/../functions/taskwarrior_parse_date.fish

@test "AST: 週一 -> sow+0d" (_task_parse_date 週一) = "sow+0d"
@test "AST: 週二 -> sow+1d" (_task_parse_date 週二) = "sow+1d"
@test "AST: 週三 -> sow+2d" (_task_parse_date 週三) = "sow+2d"
@test "AST: 週四 -> sow+3d" (_task_parse_date 週四) = "sow+3d"
@test "AST: 週五 -> sow+4d" (_task_parse_date 週五) = "sow+4d"
@test "AST: 週六 -> sow+5d" (_task_parse_date 週六) = "sow+5d"
@test "AST: 週日 -> sow+6d" (_task_parse_date 週日) = "sow+6d"

@test "AST: 周一 -> sow+0d" (_task_parse_date 周一) = "sow+0d"
@test "AST: 周二 -> sow+1d" (_task_parse_date 周二) = "sow+1d"
@test "AST: 周三 -> sow+2d" (_task_parse_date 周三) = "sow+2d"
@test "AST: 周四 -> sow+3d" (_task_parse_date 周四) = "sow+3d"
@test "AST: 周五 -> sow+4d" (_task_parse_date 周五) = "sow+4d"
@test "AST: 周六 -> sow+5d" (_task_parse_date 周六) = "sow+5d"
@test "AST: 周日 -> sow+6d" (_task_parse_date 周日) = "sow+6d"

@test "AST: 這週三 -> sow+2d" (_task_parse_date 這週三) = "sow+2d"
@test "AST: 這周三 -> sow+2d" (_task_parse_date 這周三) = "sow+2d"
@test "AST: 这周三 -> sow+2d" (_task_parse_date 这周三) = "sow+2d"

@test "AST: 這個週三 -> sow+2d" (_task_parse_date 這個週三) = "sow+2d"
@test "AST: 這個周三 -> sow+2d" (_task_parse_date 這個周三) = "sow+2d"
@test "AST: 这个周三 -> sow+2d" (_task_parse_date 这个周三) = "sow+2d"

@test "AST: 上週五 -> sopw+4d" (_task_parse_date 上週五) = "sopw+4d"
@test "AST: 上周五 -> sopw+4d" (_task_parse_date 上周五) = "sopw+4d"
@test "AST: 上個週五 -> sopw+4d" (_task_parse_date 上個週五) = "sopw+4d"
@test "AST: 上個周五 -> sopw+4d" (_task_parse_date 上個周五) = "sopw+4d"
@test "AST: 上个周五 -> sopw+4d" (_task_parse_date 上个周五) = "sopw+4d"

@test "AST: 下週二 -> sonw+1d" (_task_parse_date 下週二) = "sonw+1d"
@test "AST: 下周二 -> sonw+1d" (_task_parse_date 下周二) = "sonw+1d"
@test "AST: 下個週二 -> sonw+1d" (_task_parse_date 下個週二) = "sonw+1d"
@test "AST: 下個周二 -> sonw+1d" (_task_parse_date 下個周二) = "sonw+1d"
@test "AST: 下个周二 -> sonw+1d" (_task_parse_date 下个周二) = "sonw+1d"

@test "AST: 星期一 -> sow+0d" (_task_parse_date 星期一) = "sow+0d"
@test "AST: 星期二 -> sow+1d" (_task_parse_date 星期二) = "sow+1d"
@test "AST: 星期三 -> sow+2d" (_task_parse_date 星期三) = "sow+2d"
@test "AST: 星期四 -> sow+3d" (_task_parse_date 星期四) = "sow+3d"
@test "AST: 星期五 -> sow+4d" (_task_parse_date 星期五) = "sow+4d"
@test "AST: 星期六 -> sow+5d" (_task_parse_date 星期六) = "sow+5d"
@test "AST: 星期日 -> sow+6d" (_task_parse_date 星期日) = "sow+6d"
@test "AST: 星期天 -> sow+6d" (_task_parse_date 星期天) = "sow+6d"

@test "AST: 這星期六 -> sow+5d" (_task_parse_date 這星期六) = "sow+5d"
@test "AST: 这星期六 -> sow+5d" (_task_parse_date 这星期六) = "sow+5d"
@test "AST: 這個星期六 -> sow+5d" (_task_parse_date 這個星期六) = "sow+5d"
@test "AST: 这个星期六 -> sow+5d" (_task_parse_date 这个星期六) = "sow+5d"

@test "AST: 上星期日 -> sopw+6d" (_task_parse_date 上星期日) = "sopw+6d"
@test "AST: 上星期天 -> sopw+6d" (_task_parse_date 上星期天) = "sopw+6d"
@test "AST: 上個星期日 -> sopw+6d" (_task_parse_date 上個星期日) = "sopw+6d"
@test "AST: 上個星期天 -> sopw+6d" (_task_parse_date 上個星期天) = "sopw+6d"
@test "AST: 上个星期日 -> sopw+6d" (_task_parse_date 上个星期日) = "sopw+6d"
@test "AST: 上个星期天 -> sopw+6d" (_task_parse_date 上个星期天) = "sopw+6d"

@test "AST: 下星期日 -> sonw+6d" (_task_parse_date 下星期日) = "sonw+6d"
@test "AST: 下星期天 -> sonw+6d" (_task_parse_date 下星期天) = "sonw+6d"
@test "AST: 下個星期日 -> sonw+6d" (_task_parse_date 下個星期日) = "sonw+6d"
@test "AST: 下個星期天 -> sonw+6d" (_task_parse_date 下個星期天) = "sonw+6d"
@test "AST: 下个星期日 -> sonw+6d" (_task_parse_date 下个星期日) = "sonw+6d"
@test "AST: 下个星期天 -> sonw+6d" (_task_parse_date 下个星期天) = "sonw+6d"

@test "AST: 禮拜一 -> sow+0d" (_task_parse_date 禮拜一) = "sow+0d"
@test "AST: 禮拜二 -> sow+1d" (_task_parse_date 禮拜二) = "sow+1d"
@test "AST: 禮拜三 -> sow+2d" (_task_parse_date 禮拜三) = "sow+2d"
@test "AST: 禮拜四 -> sow+3d" (_task_parse_date 禮拜四) = "sow+3d"
@test "AST: 禮拜五 -> sow+4d" (_task_parse_date 禮拜五) = "sow+4d"
@test "AST: 禮拜六 -> sow+5d" (_task_parse_date 禮拜六) = "sow+5d"
@test "AST: 禮拜日 -> sow+6d" (_task_parse_date 禮拜日) = "sow+6d"
@test "AST: 禮拜天 -> sow+6d" (_task_parse_date 禮拜天) = "sow+6d"

@test "AST: 礼拜一 -> sow+0d" (_task_parse_date 礼拜一) = "sow+0d"
@test "AST: 礼拜二 -> sow+1d" (_task_parse_date 礼拜二) = "sow+1d"
@test "AST: 礼拜三 -> sow+2d" (_task_parse_date 礼拜三) = "sow+2d"
@test "AST: 礼拜四 -> sow+3d" (_task_parse_date 礼拜四) = "sow+3d"
@test "AST: 礼拜五 -> sow+4d" (_task_parse_date 礼拜五) = "sow+4d"
@test "AST: 礼拜六 -> sow+5d" (_task_parse_date 礼拜六) = "sow+5d"
@test "AST: 礼拜日 -> sow+6d" (_task_parse_date 礼拜日) = "sow+6d"
@test "AST: 礼拜天 -> sow+6d" (_task_parse_date 礼拜天) = "sow+6d"

@test "AST: 這禮拜五 -> sow+4d" (_task_parse_date 這禮拜五) = "sow+4d"
@test "AST: 这礼拜五 -> sow+4d" (_task_parse_date 这礼拜五) = "sow+4d"
@test "AST: 這個禮拜五 -> sow+4d" (_task_parse_date 這個禮拜五) = "sow+4d"
@test "AST: 这个礼拜五 -> sow+4d" (_task_parse_date 这个礼拜五) = "sow+4d"

@test "AST: 上禮拜一 -> sopw+0d" (_task_parse_date 上禮拜一) = "sopw+0d"
@test "AST: 上礼拜一 -> sopw+0d" (_task_parse_date 上礼拜一) = "sopw+0d"
@test "AST: 上個禮拜一 -> sopw+0d" (_task_parse_date 上個禮拜一) = "sopw+0d"
@test "AST: 上个礼拜一 -> sopw+0d" (_task_parse_date 上个礼拜一) = "sopw+0d"

@test "AST: 下禮拜五 -> sonw+4d" (_task_parse_date 下禮拜五) = "sonw+4d"
@test "AST: 下礼拜五 -> sonw+4d" (_task_parse_date 下礼拜五) = "sonw+4d"
@test "AST: 下個禮拜五 -> sonw+4d" (_task_parse_date 下個禮拜五) = "sonw+4d"
@test "AST: 下个礼拜五 -> sonw+4d" (_task_parse_date 下个礼拜五) = "sonw+4d"
